# Smoke tests estruturais (sem PHP no PATH)
# Run: powershell -File tests/run_smoke.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$failed = 0
$passed = 0

function Assert-True($cond, $msg) {
  if ($cond) {
    $script:passed++
    Write-Host "[PASS] $msg"
  } else {
    $script:failed++
    Write-Host "[FAIL] $msg" -ForegroundColor Red
  }
}

Assert-True (Test-Path "$root\setup.php") "setup.php exists"
Assert-True (Test-Path "$root\hook.php") "hook.php exists"
Assert-True (Test-Path "$root\inc\install.inc.php") "install.inc.php exists"
Assert-True (Test-Path "$root\inc\layout.inc.php") "layout.inc.php exists"
Assert-True (Test-Path "$root\inc\tv_pair.inc.php") "tv_pair.inc.php exists"
Assert-True (Test-Path "$root\public\tv_pair.php") "tv_pair.php exists"
Assert-True (Test-Path "$root\public\shell.php") "shell.php exists"
Assert-True (Test-Path "$root\locales\pt_BR.po") "pt_BR.po"

$setup = Get-Content "$root\setup.php" -Raw
Assert-True ($setup -match "2\.34\.1") "version 2.34.1"
Assert-True ((Get-Content "$root\README.md" -Raw) -match "2\.34\.1") "README version 2.34.1"
Assert-True ($setup -notmatch "::createFirstAccess") "setup init sem createFirstAccess"
Assert-True ($setup -notmatch "migrateModuleRights") "setup init sem migrateModuleRights"
Assert-True ((Get-Content "$root\inc\profile.class.php" -Raw) -match "Must stay cheap") "initProfile barato (sem migrate)"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "skipCollect") "bi skipCollect"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-bi-edit-only") "bi edit-only CSS"
Assert-True (Test-Path "$root\public\js\gridstack\gridstack-all.js") "gridstack-all.js"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "gridstack-all\.js") "studio loads all.js"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ensureGridStack") "ensureGridStack"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "function refreshBoard") "refreshBoard draft"
Assert-True ((Get-Content "$root\public\ajax\bi_board.php" -Raw) -match "layout_override") "bi_board draft"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho_bi_fs_btn") "bi fullscreen btn"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-bi-kiosk-open") "bi kiosk CSS"
Assert-True ((Get-Content "$root\public\views\map.php" -Raw) -match "map/css/leaflet\.css") "map leaflet css path"
Assert-True ((Get-Content "$root\public\views\map.php" -Raw) -match "invalidateSize") "map invalidateSize"
Assert-True (Test-Path "$root\inc\services\assets.php") "assets service"
Assert-True (Test-Path "$root\public\ajax\assets_board.php") "assets_board ajax"
Assert-True (Test-Path "$root\public\ajax\assets_list.php") "assets_list ajax"
Assert-True (Test-Path "$root\public\ajax\assets_item.php") "assets_item ajax"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "assets_board\.php") "assets polls board"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "assets_list\.php") "assets list endpoint"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "assets_item\.php") "assets item endpoint"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "ho_as_view_list") "assets list view"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "ho_as_view_item") "assets item view"
Assert-True ((Get-Content "$root\public\views\assets.php" -Raw) -match "Open in GLPI") "assets Open in GLPI msgid"
Assert-True ((Get-Content "$root\inc\services\assets.php" -Raw) -match "plugin_paineldebordo_assets_list") "assets_list function"
Assert-True ((Get-Content "$root\inc\services\assets.php" -Raw) -match "plugin_paineldebordo_assets_item") "assets_item function"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-assets-lists") "assets CSS"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-as-crumb") "assets crumb CSS"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Abrir no GLPI"') "pt_BR Abrir no GLPI"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Voltar"') "pt_BR Voltar"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Sem resultados"') "pt_BR Sem resultados"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Usado"') "pt_BR Usado"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Livre"') "pt_BR Livre"
Assert-True ((Get-Content "$root\inc\install.inc.php" -Raw) -match "config_pdbnew") "config value TEXT rebuild"
Assert-True ((Get-Content "$root\inc\install.inc.php" -Raw) -match "plugin_paineldebordo_widen_config_value_column") "widen config helper"
Assert-True ((Get-Content "$root\inc\install.inc.php" -Raw) -match "plugin_paineldebordo_trace") "install trace helper"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "Aberto agora") "pt_BR Open now"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "PREF_ICONS") "home prefs icons"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "appendChild\(modal\)") "fullscreen to body"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "flex: 1 1 9\.5rem") "KPI flex fill"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "z-index: 4000") "fs z-index"
Assert-True ((Get-Content "$root\docs\VERSIONING.md" -Raw) -match "Interface em PT-BR") "VERSIONING PT-BR rule"
Assert-True (Test-Path "$root\inc\services\bi.php") "bi.php"
Assert-True (Test-Path "$root\public\views\bi_studio.php") "bi_studio.php"
Assert-True (Test-Path "$root\public\ajax\bi_board.php") "bi_board.php"
Assert-True (Test-Path "$root\public\ajax\bi_layout.php") "bi_layout.php"
Assert-True (Test-Path "$root\public\js\gridstack\gridstack.min.js") "gridstack vendored"
Assert-True ((Get-Content "$root\public\shell.php" -Raw) -match "bi_studio\.php") "shell bi_studio"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "BI', 'paineldebordo") "nav BI"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "GridStack") "studio GridStack"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-bi-canvas") "BI CSS"
Assert-True (Test-Path "$root\inc\icons.inc.php") "icons.inc.php exists"
Assert-True (Test-Path "$root\public\views\config_hub.php") "config_hub.php"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "ho-check-list") "config entity check-list"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -notmatch "multiple size=") "config no legacy multi-select"
Assert-True ((Get-Content "$root\public\views\report_run.php" -Raw) -match "ho-toolbar") "report toolbar"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "\.ho-select") "CSS ho-select"
Assert-True (Test-Path "$root\public\ajax\map_coord.php") "map_coord.php"
Assert-True (Test-Path "$root\docs\VERSIONING.md") "VERSIONING.md"
Assert-True ((Get-Content "$root\docs\VERSIONING.md" -Raw -Encoding utf8) -match "PATCH") "VERSIONING documents PATCH"
Assert-True ((Get-Content "$root\docs\VERSIONING.md" -Raw -Encoding utf8) -match "Nunca retirar") "VERSIONING golden no-remove"
Assert-True (Test-Path "$root\docs\ARCHITECTURE.md") "ARCHITECTURE.md"
Assert-True ((Get-Content "$root\docs\TESTING.md" -Raw) -match "Kaspersky") "TESTING Kaspersky note"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-tokens-inline") "layout inlines CSS tokens"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "plugin_paineldebordo_asset_base") "asset_base helper"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "getWebDir\('paineldebordo',\s*true\)") "asset_base uses getWebDir full"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "plugin_paineldebordo_absolute_url") "absolute_url helper"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "plugin_paineldebordo_url_debug") "url_debug helper"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "absolute_url") "config TV uses absolute_url"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "tv_pair_debug") "config TV debug link"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "tv_pair_debug") "tv_pair debug"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "PAIR_AJAX_LIST") "tv_pair multi ajax"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "grid-row:\s*1\s*/\s*span\s*3") "park tile icon spans rows"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Mostrar debug da URL da TV"') "pt_BR TV debug"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-nav__icon") "nav icons"
Assert-True ((Get-Content "$root\inc\access.inc.php" -Raw) -match "canModule") "access canModule"
Assert-True ((Get-Content "$root\inc\access.inc.php" -Raw) -match "isSuperAdminStrict") "access SuperAdminStrict"
Assert-True ((Get-Content "$root\inc\profile.class.php" -Raw) -match "plugin_paineldebordo_tickets") "profile tickets right"
Assert-True ((Get-Content "$root\inc\profile.class.php" -Raw) -match "migrateModuleRights") "profile migrate modules"
Assert-True ((Get-Content "$root\public\shell.php" -Raw) -match "page_module") "shell page module gate"
Assert-True (Test-Path "$root\public\img\favicon.svg") "favicon.svg"
Assert-True ((Get-Content "$root\public\img\favicon.svg" -Raw) -match "#e73e11") "favicon brand color"
Assert-True (Test-Path "$root\public\favicon.php") "favicon.php"
Assert-True ((Get-Content "$root\inc\branding.inc.php" -Raw) -match "'favicon'") "branding favicon key"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "brand_favicon") "config favicon input"
Assert-True ($setup -match "favicon\\.php") "firewall favicon"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "Date\.now\(\) \+ ttlSec") "countdown from ttl_sec"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "favicon_href") "layout favicon dynamic"
Assert-True ((Get-Content "$root\hook.php" -Raw) -match "table count created") "install step count log"
Assert-True ((Get-Content "$root\hook.php" -Raw) -match "TV pairing table ready") "install step TV log"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "'resources'\s*=>") "resources icon"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "min '") "countdown minutes label"

Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "_audioDefaults2273") "TV audio migrate flag"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "tryPairFetch\(\s*'action=create") "tv_pair create query"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "tv_pair_api\.php") "tv_pair prefers api endpoint"
Assert-True (Test-Path "$root\public\tv_pair_api.php") "tv_pair_api.php"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "Pair TV") "nav Pair TV"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "Open logged-in TV") "nav Open logged-in TV"
Assert-True ((Get-Content "$root\setup.php" -Raw) -match "registerPluginStatelessPath") "TV stateless CSRF bypass"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "url_is_loopback") "absolute_url loopback guard"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "pushTipToast") "TV tip toast"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "pushTipToast\(I18N\.muteTip,\s*undefined,\s*3000\)") "TV tip every load 3s"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "toggleAudioFromUser") "TV toggleAudioFromUser"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "ctrlKey") "TV CTRL+M"
Assert-True ((Get-Content "$root\public\ajax\bi_board.php" -Raw) -match "requireModuleJson\('analysis', READ\)") "bi_board analysis READ"
Assert-True ((Get-Content "$root\public\ajax\bi_layout.php" -Raw) -match "requireModuleJson\('analysis', UPDATE\)") "bi_layout analysis UPDATE"
Assert-True ((Get-Content "$root\public\ajax\overview_layout.php" -Raw) -match "requireModuleJson\('analysis', UPDATE\)") "overview_layout analysis UPDATE"
Assert-True ((Get-Content "$root\public\ajax\assets_board.php" -Raw) -match "requireModuleJson\('resources', READ\)") "assets_board resources READ"
Assert-True ((Get-Content "$root\public\ajax\map_coord.php" -Raw) -match "requireModuleJson\('resources', UPDATE\)") "map_coord resources UPDATE"
Assert-True ((Get-Content "$root\docs\QA_ADVERSARIAL.md" -Raw) -match "P8") "QA adversarial personas"
Assert-True (Test-Path "$root\docs\PERMISSIONS.md") "PERMISSIONS.md"
Assert-True (Test-Path "$root\docs\QA_ADVERSARIAL.md") "QA_ADVERSARIAL.md"
Assert-True (Test-Path "$root\tests\run_acl_tests.php") "run_acl_tests.php"
Assert-True ((Get-Content "$root\tests\run_all.php" -Raw) -match "run_acl_tests") "run_all wires acl suite"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "canConfigure") "nav config gated"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-nav-group") "nav groups"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match '!\$isTop && \$isActiveGroup') "top nav closed on load"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgid "All entities"') "pt_BR All entities msgid"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Todas as entidades"') "pt_BR Todas as entidades"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-chip") "period chips"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-select") "group ho-select"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho-filters__period") "filters period group"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -notmatch "form-select-sm") "no form-select-sm in layout"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "plugin_paineldebordo_nav_tree") "nav_tree"
Assert-True ((Get-Content "$root\inc\filters.inc.php" -Raw) -match "plugin_paineldebordo_period_label") "period_label"
Assert-True ((Get-Content "$root\public\shell.php" -Raw) -match "page === 'config'") "shell config page"
Assert-True ((Get-Content "$root\public\shell.php" -Raw) -match "canConfigure") "config Super-Admin gate"
Assert-True ((Get-Content "$root\public\map\insert_coord.php" -Raw) -match "checkModule") "insert_coord module gate"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "code\.highcharts\.com") "home has CDN fallback"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-kpi__icon") "home KPI icons"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-kpi-grid--rich") "home rich KPI strip"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-quick-nav") "home shortcut cards"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-dash-spotlight") "home spotlight charts"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-chart-fs") "home fullscreen modal"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "overview_board\.php") "home overview_board"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-queue-strip") "home queue strip"
Assert-True (Test-Path "$root\public\ajax\overview_board.php") "overview_board.php"
Assert-True (Test-Path "$root\inc\services\overview_layout.php") "overview_layout.php"
Assert-True (Test-Path "$root\public\ajax\overview_layout.php") "overview_layout ajax"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "Customize mural") "home customize mural"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-prefs") "home prefs panel"
Assert-True ((Get-Content "$root\inc\services\overview_layout.php" -Raw) -match "dashboard_layout") "layout config key"
Assert-True ((Get-Content "$root\inc\services\charts.php" -Raw) -match "plugin_paineldebordo_report_period") "charts period aware"
Assert-True ((Get-Content "$root\inc\services\charts.php" -Raw) -match "'flow'") "charts catalog flow"
Assert-True ((Get-Content "$root\inc\services\charts.php" -Raw) -match "'aging'") "charts catalog aging"
Assert-True ((Get-Content "$root\public\views\chart_show.php" -Raw) -match "exportChartLocal|ho_cs_jpg") "chart_show export"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho-dash-grid") "home dash mosaic"
Assert-True ((Get-Content "$root\inc\services\overview.php" -Raw) -match "plugin_paineldebordo_chart_dataset") "overview chart_dataset"
Assert-True ((Get-Content "$root\inc\services\overview.php" -Raw) -match "plugin_paineldebordo_charts_catalog") "overview charts catalog"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "plugin_paineldebordo_overview_board") "home overview_board"
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "ho_ov_") "home chart mount prefix"
Assert-True ((Get-Content "$root\inc\services\overview.php" -Raw) -match "Opened in period', 'paineldebordo") "overview period KPI msgid"
Assert-True ((Get-Content "$root\inc\services\charts.php" -Raw) -match "plugin_paineldebordo_chart_hc_type") "chart_hc_type"
Assert-True ((Get-Content "$root\inc\services\charts.php" -Raw) -match "'requester'") "catalog requester"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-dash-grid") "CSS dash grid"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-nav-group") "CSS nav group"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw -Encoding utf8) -match 'msgstr "Configura') "pt_BR ConfiguraÃ§Ã£o"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Ano"') "pt_BR Ano"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "ajax/tv_board\.php") "tv relative board endpoint"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "ajax/tv_events\.php") "tv polls events"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "tv_toasts") "tv toast stack"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "kpi_today") "tv KPI today"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "kpi_validation") "tv KPI validation"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "kpi_solution") "tv KPI solution"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "pdb_tv_display") "tv display prefs"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "View") "tv View msgid"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "ICON_VOLUME") "tv volume icon"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "sortTickets") "tv sortTickets"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "sort: 'newest'") "tv default newest"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "date_mod") "tv card date_mod"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "oldest: false") "tv oldest KPI default off"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "flex: 1 1 0") "tv KPIs flex auto-fill"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "PREF_ICONS") "tv PREF_ICONS"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "prefIcon\(key\)") "tv col title prefIcon"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "tv-card__top") "tv card top row"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "tv-card__foot") "tv card unified foot"
Assert-True ((Get-Content "$root\inc\services\tickets.php" -Raw) -match "date DESC") "tv queues date DESC"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "ID do chamado") "pt_BR ID do chamado"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "Mais novos primeiro") "pt_BR Mais novos"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "'hash'") "icons hash"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "'sort'") "icons sort"
Assert-True ((Get-Content "$root\public\ajax\tv_events.php" -Raw) -match "date_approval") "tv events date_approval"
Assert-True ((Get-Content "$root\inc\services\tickets.php" -Raw) -match "validation_waiting") "tv validation waiting"
Assert-True ((Get-Content "$root\inc\services\tickets.php" -Raw) -match "solution_waiting") "tv solution waiting"
Assert-True ((Get-Content "$root\inc\services\tickets.php" -Raw) -match "tv_tech_name_sql") "tv tech subquery"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "'volume'") "icons volume"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "external_link") "icons external_link"
Assert-True ((Get-Content "$root\inc\icons.inc.php" -Raw) -match "'cog'\s*=>\s*'cog'") "icons cog alias"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "Abertos hoje") "pt_BR Abertos hoje"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Ver"') "pt_BR Ver"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw -Encoding utf8) -match 'msgstr "Valida') "pt_BR ValidaÃ§Ã£o"
Assert-True ((Get-Content "$root\inc\tv.inc.php" -Raw) -match "solucao_aceita") "catalog solucao_aceita"
Assert-True ($setup -match "ajax/tv_unpair") "firewall tv_unpair"
Assert-True ($setup -match '#\^/tv_pair') "firewall plugin_resource path"
Assert-True (Test-Path "$root\public\ajax\tv_unpair.php") "tv_unpair.php"
Assert-True (Test-Path "$root\public\tv_approve.php") "tv_approve.php"
Assert-True (Test-Path "$root\public\js\qrcode.min.js") "qrcode.min.js"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "validateStoredToken") "tv_pair validates token"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "tv_unpair\.php") "TV Exit unpairs"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "tv_resolve_auth") "resolve_auth helper"
Assert-True ((Get-Content "$root\inc\services\reports.php" -Raw) -match "breach_radar") "reports has breach_radar"
Assert-True ((Get-Content "$root\inc\services\reports.php" -Raw) -match "plugin_paineldebordo_reports_legacy_map") "legacy map exists"
Assert-True ((Get-Content "$root\public\views\report_run.php" -Raw) -match "export.*csv") "CSV export"
Assert-True ((Get-Content "$root\public\reports\rel_sla.php" -Raw) -match "sla_by_policy") "rel_sla redirects to sla_by_policy"
Assert-True (Test-Path "$root\_legacy_ref\README.md") "legacy ref README"
Assert-True (Test-Path "$root\public\ajax\tv_board.php") "tv_board.php"
Assert-True ((Get-Content "$root\public\tv.php" -Raw) -match "tv_board\.php") "tv uses board API"
# Stateless bootstrap guard — GLPI 11 already booted core, so no dirname(__DIR__)
# path math (breaks on Docker/volume mounts where __DIR__ is outside GLPI).
foreach ($f in @("public\ajax\tv_board.php","public\ajax\tv_events.php","public\ajax\tv_unpair.php","public\ajax\tv_pair.php","public\tv.php","public\favicon.php","public\tv_pair_api.php")) {
    $src = Get-Content "$root\$f" -Raw
    Assert-True ($src -match "if \(!defined\('GLPI_ROOT'\)\)") "$f guards bootstrap on GLPI_ROOT"
    Assert-True ($src -notmatch "dirname\(__DIR__, [45]\)") "$f drops fragile dirname path math"
}
# EVERY public entry point that bootstraps GLPI must be guarded — an unguarded
# relative include fatals under GLPI 11's LegacyFileLoadController (shell.php
# and the ajax endpoints were missed in 2.32.16 and spammed the log).
$unguarded = @()
Get-ChildItem "$root\public" -Recurse -Filter *.php | ForEach-Object {
    $s = Get-Content $_.FullName -Raw
    if ($s -match "(?m)^include\(['""](\.\./)+inc/includes\.php['""]\);") { $unguarded += $_.FullName }
}
Assert-True ($unguarded.Count -eq 0) "no unguarded relative includes.php bootstrap ($($unguarded.Count) found)"
# Logs & audit feature
Assert-True (Test-Path "$root\inc\audit.inc.php") "audit.inc.php exists"
Assert-True (Test-Path "$root\public\views\logs_hub.php") "logs_hub.php exists"
Assert-True (Test-Path "$root\public\ajax\audit.php") "audit beacon endpoint exists"
$auditSrc = Get-Content "$root\inc\audit.inc.php" -Raw
foreach ($fn in @("plugin_paineldebordo_audit_ensure_tables","plugin_paineldebordo_audit_log","plugin_paineldebordo_audit_touch","plugin_paineldebordo_audit_online","plugin_paineldebordo_audit_list","plugin_paineldebordo_audit_glpi_logins","plugin_paineldebordo_audit_retention_days","plugin_paineldebordo_audit_purge")) {
    Assert-True ($auditSrc -match [regex]::Escape("function $fn")) "audit has $fn"
}
Assert-True ($auditSrc -match "glpi_plugin_paineldebordo_accesslog") "audit accesslog table"
Assert-True ($auditSrc -match "glpi_plugin_paineldebordo_presence") "audit presence table"
# GLPI 11 deprecates DATETIME — audit DDL must use TIMESTAMP and migrate old cols
Assert-True ($auditSrc -notmatch "(?i)`` (datetime|DATETIME)") "audit DDL has no datetime column"
Assert-True ($auditSrc -match "timestamp NULL DEFAULT NULL") "audit DDL uses timestamp"
Assert-True ($auditSrc -match "plugin_paineldebordo_audit_modify_to_timestamp") "audit migrates datetime to timestamp"
# glpi_events.items_id is not the user id for login events — match by message
Assert-True ($auditSrc -match "SUBSTRING_INDEX") "glpi logins resolve user by message login"
Assert-True ($auditSrc -match "PLUGIN_PAINELDEBORDO_RETENTION_DEFAULT") "retention default constant"
Assert-True ($auditSrc -match "const PLUGIN_PAINELDEBORDO_RETENTION_DEFAULT = 30") "retention defaults to 30 days"
# 2.34.0 — real audit trail
Assert-True ($auditSrc -match "'access_denied'") "audit records denied access"
Assert-True ($auditSrc -match "'export_logs'") "audit records log export"
Assert-True ($auditSrc -match "function plugin_paineldebordo_audit_count") "audit has count for pagination"
Assert-True ($auditSrc -match "function plugin_paineldebordo_audit_users") "audit lists users for filter"
Assert-True ($auditSrc -match "function plugin_paineldebordo_audit_purge_now") "audit purge_now for cron"
Assert-True ($auditSrc -match "entities_id") "audit records active entity"
Assert-True ($auditSrc -match "glpi_plugin_paineldebordo_presence WHERE last_seen <") "purge cleans stale presence"
$shellAudit = Get-Content "$root\public\shell.php" -Raw
Assert-True (([regex]::Matches($shellAudit, "audit_log\('access_denied'")).Count -ge 3) "all 3 gates log denied access"
Assert-True ($shellAudit -match "logs_export\.php") "shell routes audit export"
Assert-True (Test-Path "$root\public\views\logs_export.php") "logs_export.php exists"
Assert-True (Test-Path "$root\inc\audit.class.php") "audit cron class exists"
$cronSrc = Get-Content "$root\inc\audit.class.php" -Raw
Assert-True ($cronSrc -match "function cronAuditpurge") "cron task method"
Assert-True ($cronSrc -match "function cronInfo") "cron info method"
Assert-True ((Get-Content "$root\hook.php" -Raw) -match "CronTask::register") "install registers audit cron"
# Warn on screen while the old ST-Dashboard is still registered: its uninstall
# does DROP TABLE without IF EXISTS on the tables we just migrated.
$hookLegacy = Get-Content "$root\hook.php" -Raw
Assert-True ($hookLegacy -match "directory = 'dashboard'") "install detects legacy ST-Dashboard"
Assert-True ($hookLegacy -match "ST-Dashboard detected") "install warns about ST-Dashboard uninstall"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "ST-Dashboard detectado") "ST-Dashboard warning translated"
Assert-True ((Get-Content "$root\inc\config_post.inc.php" -Raw) -match "touched") "config change names changed fields"
$logsView = Get-Content "$root\public\views\logs_hub.php" -Raw
Assert-True ($logsView -match "flt_user") "logs page filters by user"
Assert-True ($logsView -match "audit_count") "logs page paginates"
Assert-True ($logsView -match "tv_parse_user_agent") "logs page shows device"
# Icon-only controls must carry a tooltip (design-system golden rule)
foreach ($f in @("public\home.php","public\views\chart_show.php")) {
    $s = Get-Content "$root\$f" -Raw
    Assert-True ($s -match "ho-menu__trigger ho-tip") "$f export trigger has tooltip"
}
$shellSrc = Get-Content "$root\public\shell.php" -Raw
Assert-True ($shellSrc -match "'logs'\s*=>\s*\[") "shell view_map has logs"
Assert-True ($shellSrc -match "plugin_paineldebordo_audit_touch") "shell calls audit_touch"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "'logs'\s*=>\s*__\('Logs & audit'") "nav admin has logs item"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "function plugin_paineldebordo_user_avatar") "avatar helper for any user"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "function plugin_paineldebordo_avatar_html") "avatar_html render helper"
$hookSrc = Get-Content "$root\hook.php" -Raw
Assert-True ($hookSrc -match "plugin_paineldebordo_audit_ensure_tables") "install creates audit tables"
Assert-True ($hookSrc -match "glpi_plugin_paineldebordo_accesslog") "uninstall drops accesslog"
Assert-True ($hookSrc -match "glpi_plugin_paineldebordo_presence") "uninstall drops presence"
# JPG export no longer black — export forces an opaque white background
Assert-True ((Get-Content "$root\public\home.php" -Raw) -match "backgroundColor: '#ffffff'") "home export white bg"
Assert-True ((Get-Content "$root\public\views\chart_show.php" -Raw) -match "backgroundColor: '#ffffff'") "chart_show export white bg"
Assert-True ((Get-Content "$root\hook.php" -Raw) -match "SHOW INDEX") "install skips PK alter when ready"
Assert-True ((Get-Content "$root\hook.php" -Raw) -notmatch "PRIMARY KEY AUTO_INCREMENT") "count DDL is sane"
Assert-True (Test-Path "$root\locales\pt_BR.mo") "pt_BR.mo compiled"
Assert-True (Test-Path "$root\inc\csrf.inc.php") "csrf.inc.php"
Assert-True ((Get-Content "$root\public\ajax\tv_pair_approve.php" -Raw) -notmatch "validateCSRF") "approve has no double CSRF"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "Overview") "nav English msgid"
Assert-True ((Test-Path "$root\public\js\highcharts.js") -and ((Get-Item "$root\public\js\highcharts.js").Length -gt 1000)) "highcharts.js present"
Assert-True ($setup -match "check_prerequisites") "prerequisites hook"
Assert-True ($setup -match "PHP_VERSION") "PHP version check"
Assert-True ($setup -match "Missing table") "check_config missing tables"

$hook = Get-Content "$root\hook.php" -Raw
Assert-True ($hook -notmatch "or die\(") "hook has no or die("
Assert-True ($hook -match "plugin_paineldebordo_install_log") "install progress log"
Assert-True ($hook -match "plugin_paineldebordo_install_fail") "install fail helper"
Assert-True ($hook -match "starting installation") "install start message"
Assert-True ($hook -match "installed successfully") "install success message"

$install = Get-Content "$root\inc\install.inc.php" -Raw
Assert-True ($install -match "addMessageAfterRedirect") "uses Session messages"
Assert-True ($install -match "plugin_paineldebordo_db_ok") "db_ok helper"
Assert-True ($install -match "plugin_paineldebordo_db_ok_idempotent") "idempotent db helper"
Assert-True ($install -match "plugin_paineldebordo_db_query_idempotent") "query_idempotent helper"
Assert-True ($install -match "plugin_paineldebordo_db_has_index") "db_has_index helper"
Assert-True ((Get-Content "$root\hook.php" -Raw) -match "db_has_index\('glpi_plugin_paineldebordo_map'") "hook skips map location index"

$shell = Get-Content "$root\public\shell.php" -Raw
Assert-True ($shell -notmatch "<iframe") "shell has NO iframe"

Assert-True ((Split-Path $root -Leaf) -eq "paineldebordo") "folder name paineldebordo"

Write-Host ""
Write-Host "---"

Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "tv-pair__main") "tv_pair side-by-side layout"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "renewCode") "tv_pair auto-renew"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "tv_pair_bar") "tv_pair progress bar"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "tv_pair_ttl_seconds") "TTL helper"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "tv_pair_set_ttl") "TTL global setter"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "tv_parse_user_agent") "UA parser"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "tv_pair_set_nickname") "nickname setter"
Assert-True ((Get-Content "$root\inc\tv_pair.inc.php" -Raw) -match "device_label") "device_label column"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "tv_pair_ttl") "config TTL select"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "tv_nickname") "config nickname"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -notmatch "location\.reload\(\)") "no reload after TV link"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "shell\.php\?page=config") "GET navigate after TV link"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "Code expires in") "pt_BR timer string"
Assert-True (Test-Path "$root\docs\PROPOSTA_PERSONALIZACAO_E_MENU.md") "personalization proposal doc"

Assert-True (Test-Path "$root\public\img\logo-inovare.svg") "bundled logo expanded"
Assert-True (Test-Path "$root\public\img\logo-inovare-mark.svg") "bundled logo mark"
Assert-True (Test-Path "$root\inc\branding.inc.php") "branding.inc.php"
Assert-True ((Get-Content "$root\inc\branding.inc.php" -Raw) -match "branding_css") "branding CSS helper"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-app--rail") "rail CSS"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "logo-inovare-mark") "local collapsed logo"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "ho_nav_rail_btn") "rail toggle"
Assert-True ((Get-Content "$root\inc\filters.inc.php" -Raw) -match "nav_collapsed") "nav_collapsed pref"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "branding_save") "personalization card"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match "Personalization") "pt_BR Personalization"

Assert-True (Test-Path "$root\inc\config_post.inc.php") "config_post PRG helper"
Assert-True ((Get-Content "$root\public\shell.php" -Raw) -match "hubops_config_flash") "shell PRG flash"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "Open link") "Open link msgid"
Assert-True ((Get-Content "$root\public\tv_pair.php" -Raw) -match "PAIR_AJAX") "tv_pair absolute ajax"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "ho-app--rail \.ho-nav-group\.is-open") "rail flyout is-open"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "isRail") "rail click accordion JS"
Assert-True ((Get-Content "$root\inc\layout.inc.php" -Raw) -match "Branding MUST win") "branding after CSS links"

Assert-True ((Get-Content "$root\public\ajax\bi_layout.php" -Raw) -notmatch "validateCSRF") "bi_layout no double CSRF"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho-bi-palette__acc") "BI palette accordion"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho_bi_pal_assets_lists") "BI assets list palette"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "confirmLeaveIfDirty") "BI leave unsaved modal"
Assert-True ((Get-Content "$root\inc\services\bi.php" -Raw) -match "assets\.list\.") "BI assets list refs"
Assert-True ((Get-Content "$root\inc\services\bi.php" -Raw) -match "assets_lists") "BI palette assets_lists"
Assert-True ((Get-Content "$root\public\css\dashboard-tokens.css" -Raw) -match "scrollbar-color") "nav scrollbar DS"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -notmatch "return confirm\(") "config no native confirm"
Assert-True ((Get-Content "$root\public\views\config_hub.php" -Raw) -match "ho_cfg_modal") "config DS modal"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "X-Requested-With") "BI save XHR CSRF preserve"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "X-Glpi-Csrf-Token") "BI board refresh CSRF"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho-bi-tab-rename-ok") "BI tab rename confirm"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "Tab name updated") "BI tab rename toast msgid"
Assert-True ((Get-Content "$root\locales\pt_BR.po" -Raw) -match 'msgstr "Nome da aba atualizado') "pt_BR tab rename toast"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "grid\.on\('change'") "BI markDirty on drag"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "Layout saved") "BI save toast i18n"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho_bi_modal") "BI reset modal"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "ho-bi-period-chips") "BI period chips"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "widgetLabel") "BI PT label helper"
Assert-True ((Get-Content "$root\public\views\bi_studio.php" -Raw) -match "pdb_bi_draft") "BI draft persistence"
Write-Host "Passed: $passed  Failed: $failed"
if ($failed -gt 0) { exit 1 } else { exit 0 }
